[package]
name = "webshot"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39.3", features = ["full"] }
futures = "0.3.30"
colored = "2.1.0"
cli-table = "0.4.9"
url = "2.5.2"
rand = "0.8.5"
reqwest = { version = "0.12.7", features = ["json"] }